source config.sh

# dealing with the alias file itself
alias jal="source ${BASH_RC}" # re-source
alias jalv="vim ${ALIAS_FILE}"
alias jall="less ${ALIAS_FILE}"

# update system & auto remove old junk
alias update='sudo apt update -y && sudo apt upgrade -y sudo apt autoremove'

alias groot="cd ${GIT_BASE}"
alias gscripts="cd ${GIT_BASE}/scripts"

# shred in parallel command
alias Shred="nice -n 19 /usr/bin/ruby ~/git_projects/scripts/ruby/Executables/shred.rb"

alias sqlitestudio='/opt/SQLiteStudio/sqlitestudio'
alias sqlstudio=sqlitestudio
